### ISSUE TITLE
Overlong lines

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/SSO#14]
Some lines in the LaTeX source are long or very long, which makes understanding diffs hard.
[IvoatexDoc](https://www.ivoa.net/documents/Notes/IVOATex/) recommends _"Authors are urged to keep lines shorter than 72 characters in input
files whenever possible in order to keep diffs useful and readable."_

**Comment by bertocco** [comment]
Fixed in PR #15, can be closed.
