### ISSUE TITLE
Actions/workflows not working

### ISSUE THREAD

**Issue by bertocco** [ivoa-std/SSO#16]
As stated by @Zarquan  in a comment on PR #13, there was "a question whether GitHub will find the workflows in doc/.github/workflows". The answer after the last two merge operations is no, github does not find the workflows. So workflows need to be moved from SSO/doc/.github/workflows/ to SSO/.github/workflows/ but this has to be done carefully because the two definition files build.yml and preview.yml are created with the assumption that the basedir of the document is the root of the repo and not a subfolder

**Comment by Zarquan** [comment]
Looking at the rest of the documents in the ivoa-std organization, most of the standards have their LaTex document at the top level, but not all. Several of the data model standards follow a similar pattern to the SSO document, placing their LaTex document in a `doc` directory.

Both [CoordinateDM](https://github.com/ivoa-std/CoordinateDM) and [ProvenanceDM](https://github.com/ivoa-std/ProvenanceDM) have their LaTex document source in a `doc` directory and their `.github/worflows` at the top level.

If we want to be consistent with the other standards we could move the LaTex document from `doc` to the top level. Or, if we want to leave it as-is, then we could look at how the `.github/worflows` from [CoordinateDM](https://github.com/ivoa-std/CoordinateDM) or [ProvenanceDM](https://github.com/ivoa-std/ProvenanceDM) are configured.

**Comment by bertocco** [comment]
The LaTex document has been moved from doc to the top level and now the preview corresponding to a pull request is working, verified merging PR #20. Closing the issue.
